### ISSUE TITLE
interference undo history / jump history

### ISSUE THREAD

**Issue by JonathanSchaber** [caksoylar/kakoune-smooth-scroll#10]
I've noticed that smooth-scrolling seems to interfere with the undo / jump history:

e.g. when I accidentally hit «gg» (happens often when I quickly want to move several characters to the left), «c-o» doesn't take me back to the location I was before.

Same for undoing: sometimes I want to undo an action and it reads: 
```
'smooth-scroll-execute-keys' 3:5: 'evaluate-commands' 2:9: 'execute-keys' nothing left to undo
```

Just wanted to mention this, sorry for not being able to rapport a more reproducible issue!

**Comment by caksoylar** [comment]
Thanks for the report!

About the jumplist: I never noticed that Kakoune pushes the previous position to the jump list when you use a `goto` command, but that is indeed mentioned in `:doc keys jump-list`. Like you noticed smooth-scroll breaks this behavior since we don't literally use the `goto` commands but emulate it. I'll investigate what commands are supposed to save to the jump list other than `goto` ones, then we can add a manual `<c-s>` for the mappings that do.

About the undo: I believe this is the same as what I explained in 2. under comment https://github.com/caksoylar/kakoune-smooth-scroll/issues/6#issuecomment-735993106, i.e. there isn't actually an undo action to do and the error message is just propagated through the smooth-scroll mapping. However let me know if you encounter a situation where there was indeed something to undo but smooth-scroll prevented it.
