### ISSUE TITLE
Add option to force absolute line numbering during scrolling and revert it to relative afterwards.

### ISSUE THREAD

**Issue by Anomalocaridid** [caksoylar/kakoune-smooth-scroll#13]
With relative line numbers enabled, the line number for the cursor stays still before snapping to the cursor's position, which is fairly jarring. I think that this could be resolved by adding an option to force the line numbers to absolute numbering while scrolling and then reverting it to relative line numbers when scrolling has finished.

**Comment by caksoylar** [comment]
Hi, I gave it some thought and a generic solution for customization seemed like a better approach than specifically handling line numbers, especially since it's hard to detect whether line numbers are enabled beforehand. In the [latest commit](https://github.com/caksoylar/kakoune-smooth-scroll/commit/3690fc6314889374e78ba0a2fa3e444f7f4da4f0) I added the possibility to define user hooks for scrolling begin and end events, so now you can experiment to improve the behavior. Below are a couple options that I tried, also showing how to use the new hooks (I'll update the README at some point as well):
```kak
hook global WinCreate .* %{ hook -once window WinDisplay .* %{
    smooth-scroll-enable

    # enable line numbers
    add-highlighter window/nl number-lines -relative -hlcursor


    # option 1: switch between relative and absolute line numbers
    hook -group smooth-scroll window User ScrollBegin %{
        add-highlighter -override window/nl number-lines
    }
    hook -group smooth-scroll window User ScrollEnd %{
        add-highlighter -override window/nl number-lines -relative -hlcursor
    }

    # option 2: blank out line numbers while scrolling
    hook -group smooth-scroll window User ScrollBegin %{
        set-face window LineNumbers black,black
        set-face window LineNumbersCursor black,black
        set-face window LineNumbersWrapped black,black
    }
    hook -group smooth-scroll window User ScrollEnd %{
        unset-face window LineNumbers
        unset-face window LineNumbersCursor
        unset-face window LineNumbersWrapped
    }
}}
```

For me option 2 is a bit too much flashing when the numbers disappear and then come back at the end. Option 1 is your suggestion and it seems OK. I personally don't mind the default relative line behavior since the relative line numbers stay the same for most of the scroll which is nice (though it is a little jarring at the end when the last jump occurs, like you said). I'd welcome if you have other ideas that would look better. I can put it as a recommendation in the README.

**Comment by Anomalocaridid** [comment]
Option 1 works perfectly for me, although I had to tweak them slightly to work with a plugin I have installed that automatically switches between absolute and relative line numbers. I certainly agree that these hooks are a much better solution than my idea for a single specific option. Thanks a lot!
