### ISSUE TITLE
Implement better support for pure-view-moving keys, like <c-u>, <c-d>

### ISSUE THREAD

**Issue by Guest0x0** [caksoylar/kakoune-smooth-scroll#2]
Hi. I have finally got time to push the hack in [the forum post](https://discuss.kakoune.com/t/a-smooth-scrolling-plugin-for-kakoune/1151/26). But I am not sure how it should be integrated, hence opening this issue for discussion.

As mentioned in the forum post, the hack implements a better smooth version of `<c-u>`,  `<c-d>`, `<c-f>` and `<c-b>`. I have been using it since I first implemented it, and it works well. But the behavior is achieved by defining a separate command for these keys, instead of a call to `scroll-do-key`. I have come up with several ways to integrate it:

1. Check in the `smooth-scroll-enable` command, when binding keys, if the key is one of `<c-u>`, `<c-d>`, `<c-f>`, `<c-b>`, if so, treat it specially. But this won't work if the user map something these to something else, or use other keys. Such condition is rare, though.

2. Add a separate option for these commands. This is very dirty, though, and requires internal knowledge concerning things like [relevant issue in kakoune](https://github.com/mawww/kakoune/issues/3616) to understand, which I don't consider a good design.

3. Simply not bind the keys, and expose the page-scrolling command. Again, this requires internal knowledge to understand, and is not consistent with the rest of the world.

What's your suggestions? And do you have any better idea to integrate the hack?

**Comment by caksoylar** [comment]
Hi, sorry I somehow managed to unwatch the repo so I didn't see this!

For me option 1 is the most appealing because 2 and 3 make configuration more inconsistent and cumbersome for the user, like you mentioned. Maybe I am misunderstanding this:
> But this won't work if the user map something these to something else, or use other keys. Such condition is rare, though.

RHS of a mapping is always supposed to map to the Kakoune built-in keys (as mappings are always nonrecursive). So if we check the RHS being equal to `<c-f>` etc., whatever the LHS is (even if user uses a different key for `<c-f>`) I don't think we'll run into problems. Since we refactored to create a `smooth-scroll-map-key` function, inside there should be the best place to add this check.

As an example, if user uses the key `<c-j>` for `<c-f>` motion, they can still specify
```
set-option global scroll_keys_normal <c-j>=<c-f> [...]
```
and we override the behavior for `<c-f>`, they would still be able to press `<c-j>` and (smoothly) move one page down. Let me know if I am missing something.

Only nit I see with this approach is we will change the `<c-f>` etc. behavior regarding moving the cursor, like you mentioned in the forum post. We can note the changed behavior in the caveats section in the README and that should be fine.
